import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable, map } from 'rxjs';
import { BaseHttpClientService } from './base-http-client.service';
import { IAppointmentModel } from '../models/appointment.model';

@Injectable({
  providedIn: 'root'
})

export class DynamicserviceService extends BaseHttpClientService {

  private baseUrl = "https://localhost:44337/Appointments";
  token: string = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjYwZDBmNmZmNmFiMjEyYWI4YTFlMzdjZGQyMDI0OThjIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE3MTQ3MTI3NjYsImV4cCI6MTcxNDc5OTE2NiwiaXNzIjoiaHR0cHM6Ly9zc2EtYXV0aG9yaXR5LnBsdC5kZXYudHJ1YnJpZGdlLmNvbSIsImF1ZCI6Im5vdGVzIiwiY2xpZW50X2lkIjoiVGhyaXZlIiwic3ViIjoic2hhdW56IiwiYXV0aF90aW1lIjoxNzE0NzEyNzY2LCJpZHAiOiJodHRwczovL3NzYS1hdXRob3JpdHkucGx0LmRldi50cnVicmlkZ2UuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJzaGF1bnoiLCJodHRwOi8vaGVhbHRobGFuZC5jb20vMjAxNS8wNC9pZGVudGl0eS9jbGFpbXMvdXNlcnhyZWYiOiJzaGF1bnoiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJTaGFyb24iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiSGF1bnoiLCJ1cm46Y3BzaTp0aW1lem9uZTpkaXNwbGF5IjoiQ0RUIiwidXJuOmNwc2k6dGltZXpvbmU6b2Zmc2V0IjoiLTIxNjAwMDAwIiwidXJuOmNwc2k6dGltZXpvbmU6ZHN0Om9mZnNldCI6IjM2MDAwMDAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsidXNlciIsInBhdGllbnRDb25uZWN0QWN0aXZlOnRydWUiLCJwaHlzIl0sImRlYSI6IjIxMzEyMyIsInpvbmVpbmZvIjoiQ2VudHJhbCBTdGFuZGFyZCBUaW1lIiwicHJhY3RJZCI6IjIuMS4wLjAuc2hhdW56Ljk5OTk5NS4wIiwidGltZXpvbmUiOiJDZW50cmFsIERheWxpZ2h0IFRpbWUiLCJ1cm46Y3BzaTppZGVudGl0eTp1c2VyaWRlbnRpZmllciI6InNoYXVueiIsImxvY2FsZSI6ImVuLVVTIiwiY2FyZF9saXN0IjoiZnVsbF9saXN0IiwidGlkIjoiZnNkYi0yMTA3IiwidXJuOmNwc2k6dGhyaXZlOnVuYW1lIjoibDIxMDciLCJ1cm46Y3BzaTppZGVudGl0eTpjdXN0b21lcmlkZW50aWZpZXIiOiJmc2RiLTIxMDciLCJvcmdOcGlzIjpbIjEyMzQ1Njc4OTMiLCIxNzMwMTE1OTQwIl0sImVtYWlsIjoiIiwidXJuOmNwc2k6aWRlbnRpdHk6c3RhZmZ0eXBlIjoiUGh5c2ljaWFuIEdyb3VwIiwiZW1haWxfdmVyaWZpZWQiOiJ0cnVlIiwiZmFjaWRzIjpbIjIiLCI1OCIsIjU5Il0sIm5waSI6IjEyMzIyMyIsInBob25lX251bWJlcl92ZXJpZmllZCI6InRydWUiLCJ1cm46Y3BzaTppZGVudGl0eTpzb3VyY2VzeXN0ZW0iOiJ0aHJpdmUiLCJncm91cHMiOiJzeXNhZG1pbiIsImFyaWRzIjpbIjEiLCI1OCIsIjU5Il0sImdpdmVuX25hbWUiOiJTaGFyb24iLCJ1cm46Y3BzaTp0aHJpdmU6Y3VzdG9tZXJfbnVtYmVycyI6IjIxMDciLCJvcmdfaWQiOlsiaWQtb3NmYWMuZDRmMDcwMDgtMGNjYi00NmFkLTlkMmYtMzJiMDM1YTVmNzhjIiwiaWQtb3NmYWMuZWY5ZTg0YmUtM2JlYy00Y2E2LTlkYzItY2M1ZjBhMGZiNWRhIiwiaWQtb3NmYWMuMzczMDllNzYtMGZiNy00MGZhLWExYTEtYzlmZTAyMGNjYmMxIl0sIm5hbWUiOiJTaGFyb24gSGF1bnoiLCJwaG9uZV9udW1iZXIiOiIwIiwiZmFtaWx5X25hbWUiOiJIYXVueiIsImp0aSI6IllfXzBvYjFWQlhTS09lWHRmakRrSVEiLCJzY29wZSI6WyJvcGVuaWQiLCJub3RlcyJdLCJhbXIiOlsic3drIl19.gkGhwM5jSVJfKl2VCCZqqr-vUBYU-JA1skbHE5041dvRnXV2E1u-_JHKx-DdORScdZLfnSKkDI4J4HEHC-CtA7Xbvq_PY4uendNwB4fSsYBQgEe-TB0rlP8DE8OAY35EVh0fp5YSrQurQXpiXkuiGtxtpOPbCiJai1WVcpMn1ZQU7BVui2KoCNcETW4F-gqfFyRk3VuU2ELK2m0LBp9BxE4PsiK0SExyoWFE31YTL6GosFB0zC8R64HE-JPcbYgrGewMs2arrpSpwe8SPFBFtYYSr2It84u3akJQ9nx9zGHY3uzhnedynuXs_T3dXXbr146eJoX3_6Av-9vnhT54xg";
  constructor(private http: HttpClient) {
    super();
  };

  getAppointmentsById(appointmentIds: string[]): Observable<IAppointmentModel[]> {
    const headers = new HttpHeaders()
      .set('Authorization', 'Bearer ' + this.token);
    let result = this.http.get(`${this.baseUrl}/GetAppointments?appointmentsId=${appointmentIds}`, { 'headers': headers }).pipe(
      map(this.extractDataFromResponse));
    return result;

  }
}
